export default {
    SET_TEST: "setTest",
    SET_SEARCHALLLIST: "SET_SEARCHALLLIST",
    SEARCH_BYKEYWORD: "SET_SEARCHBYKEYWORD",
    SET_SEARCHLIST: "SET_SEARCHLIST",
    SEARCH_BOARD: "SEARCH_BOARD",
    SET_BOARD: "SET_BOARD"

};