export default {
    SET_TEST: "setTest",
    SET_SEARCHALLLIST: "SET_SEARCHALLLIST",
    SET_SEARCHLIST: "SET_SEARCHLIST",
    SET_BOARD: "SET_BOARD",
    SET_COMMENTLIST: "SET_COMMENTLIST",
    SEARCH_BYKEYWORD: "SET_SEARCHBYKEYWORD",
    SEARCH_BOARD: "SEARCH_BOARD",
    SEARCH_BYDISTANCE: "SEARCH_BYDISTANCE",
    LOAD_COMMENTLIST: "LOAD_COMMENTLIST",
};